### ISSUE TITLE
"Get_First_Main_File_Name" not declared in "Osint"

### ISSUE THREAD

**Issue by Earnestly** [AdaCore/spark2014#11]
New build failure:

```
gprbuild  -Pgnat2why -j0 -cargs -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -largs -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
Compile
   [Ada]          gnat1drv.adb
   [C]            smissing.c
   [Ada]          atree.adb
   [Ada]          back_end.adb
   [Ada]          checks.adb
   [Ada]          comperr.adb
   [Ada]          csets.adb
back_end.adb:168:46: "Get_First_Main_File_Name" not declared in "Osint"

   compilation of back_end.adb failed

gprbuild: *** compilation phase failed
```

**Comment by kanigsson** [comment]
That's indeed a new function in the GNAT sources - I suspect this will be merged with FSF sources soon (if that's what you are using).

**Comment by yannickmoy** [comment]
btw, you will not have this problem if you use the "fsf" branch of spark2014, which is meant to follow the changes on FSF sources, as documented in the README: 
https://github.com/AdaCore/spark2014/#62-building-spark-with-gnat-fsf

**Comment by yannickmoy** [comment]
You need to use the "fsf" branch of spark2014 repo as I indicated.

**Comment by pmderodat** [comment]
Hello @Earnestly 

At this point we can’t do much more: while we guarantee that the `fsf` branch of `spark2014` can be built against the current `trunk` of GCC at the FSF, we cannot provide the same guarantee for the `master` branch, as it needs corresponding changes in GNAT. What we do is that we update the `fsf` branch to follow `master` as soon as we could port the required GNAT changes at the FSF.

Note that since GCC development at the FSF reached stage 4, we currently can’t port GNAT changes anymore, probably until April (once GCC is branched and we switch back to stage 1).

**Comment by Earnestly** [comment]
So let's leave this open until the changes needed are available from GCC.  I'm not going to use the `fsf` branch.

**Comment by pmderodat** [comment]
Ok. :-) Yes, as I said, since GCC is currently in a stabilization process, our regular efforts to port our internal GNAT patches to the FSF are paused. The purpose of the `fsf` branch here is precisely to let anyone build `spark2014` with the most recent GCC sources at the FSF. We update this branch to follow `master` every time we port patches to the FSF. So we’re already doing our best.
