### ISSUE TITLE
Wish: global and depends implicit annotations improvement.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/spark2014#16]
Hello,
Global annotations are somewhat annoying, either you don't add any Global annotation then there are implicit but you don't know easily which ones are set or you add annotations but you must add annotations at all levels.
It should be easier to use.
One global annotation should be possible to be added explicitly without adding all others, the others remaining implicit, unless the explicit global annotation is incorrect or illegal thus an error is reported.
Likewise, an gnatprove option might be added in order to display the implicit annotations as info messages.
Same idea for Depends annotations.
What is your feedback?
Thanks, Pascal.

**Comment by yannickmoy** [comment]
Hi Pascal, I'm surprised that you say Global/Depends need to be put nowhere or everywhere. A main design decision in the new techno (since 2014) was precisely to allow much more flexibility. Do you have an example that you can share?

The other side of your question, about displaying computed contracts, is something we've discussed many time, but it's not immediate to do. So given everything else in the roadmap, this has not made it to our roadmap yet. At the same time, we always thought of displaying in an IDE, not as info messages, or (probably better) as JSON in the generated .spark files. That way, anyone could extract the info for their own needs.

**Comment by Blady-Com** [comment]
Sorry Yannick, my memory and wording was confused.
My issue is you can't add a Global (or Depends) specification on a subprogram with partial global list, as in the following example:

```ada
 1. package body PT12 with SPARK_Mode is

 3.    G2 : Integer := 99;
 4.    G3 : Integer;
 5.    pragma Import (C, G3);

11.    procedure P2 (V : out Integer) is
12.    begin
13.       V := G2 + G3;
14.    end P2;

25.    procedure PP2a (VV : out Integer) with Global => (Input => G2) is
26.       V : Integer;
27.    begin
28.       P2 (V);
29.       VV := V;
30.    end PP2a;

```
gnatprove ouput:
`pt12.adb:13:17: high: "G3" must be listed in the Global aspect of "PP2a" (SPARK RM 6.1.4(13)), in call inlined at pt12.adb:28
`
If I write:
`   procedure PP2a (VV : out Integer) is
`
then all is fine for gnatprove.

When nothing is specified, gnatprove makes implicit global contracts.
When I want to specify only G2 global then I must also specify G3. It is no more implicit.
I agree, the contract shouldn't lie: G2 is not the only global.
But, but, in my opinion, the contract Global (as others such as Pre or Post) is a programmer specification the program should hold.
In Post specification, for instance, the programmer puts what it seems to him mandatory to hold. It is not exhaustive.
In my opinion, Global should behave like that. The programmer puts the globals which seem to him mandatory to check. It might be not exhaustive.
In a way, "with Global => (Input => G2)" doesn't lie: it should say only that G2 is a global of the subprogram, not all of them.
My intend is that I expect the prover to check a specific list of globals but not all the used globals, maybe in deep levels of subprograms that is somewhat annoying to list (possibly with creation of some abstract states, etc).
As this way of thinking could cause backward compatibilities, may be a new name might be found such as: Specific_Global (same for Specific_Depends and Specific_Refined_Global).
What is your feedback?

**Comment by yannickmoy** [comment]
@Blady-Com it would be possible indeed to invent such a partial contract, either separately from Global, or as a variant of Global (say, adding "others" in a list to indicate it is a partial list of input, output or in-out). I'm not sure it's important enough to warrant such an effort though, so it needs gathering user support for this feature first. 

As an alternative to language support, or until there is language support for that feature, one way to allow users to check such properties would be for GNATprove to output the generated Global contracts in .spark JSON files, so that any user can extract this info for their own checking.

**Comment by spanners** [comment]
> As an alternative to language support, or until there is language support for that feature, one way to allow users to check such properties would be for GNATprove to output the generated Global contracts in .spark JSON files, so that any user can extract this info for their own checking.

This is now supported by GNATprove when the `--flow-show-gg` switch is specified. A .gg JSON file is created for each program unit, inside the gnatprove/ folder. There is a plugin for GNATstudio that extracts this info, available here: https://github.com/AdaCore/gps/blob/master/share/plug-ins/show_globals.py

**Comment by yannickmoy** [comment]
Given that you can now see the Global contract internally generated by the tool, it's easy to include that generated contract directly or after making it more precise inside your code. I'll close this issue as a result.
