### ISSUE TITLE
Trying to build a set-up script for a Debian development box

### ISSUE THREAD

**Issue by martin-cs** [AdaCore/spark2014#35]
Hi all,

I want to be able to set up a Debian image so that I can build SPARK 2014.  Ideally this would be a script but if a few steps have to be manual then that is probably OK.  I have followed the build instructions where I can but have run into some difficulties; please could you help?

1. Install the dependencies described here:
https://github.com/AdaCore/spark2014/blob/33f3c141e821d980d2ed99cbcb2892646e53f266/README.md?plain=1#L71
```
apt-get install ocaml menhir libnum-ocaml-dev libmenhir-ocaml-dev python3-sphinx
```

2. Install the GNAT 2020 Community edition:
```
wget 'https://community.download.adacore.com/v1/a639696a9fd3bdf0be21376cc2dc3129323cbe42?filename=gnat-2020-20200818-x86_64-linux-bin&rand=376' -o gnat-2020-20200818-x86_64-linux-bin
chmod 755 gnat-2020-20200818-x86_64-linux-bin
./gnat-2020-20200818-x86_64-linux-bin
```

3. Clone the repo including submodules:
```
git clone https://github.com/AdaCore/spark2014.git
cd spark2014
git submodule init
git submodule update --recursive
git checkout gpl-2020
```
( Is there a more modern version than the GPL-2020 one?  Will there be a GPL-2021 or a GPL-2022 version? )

4. I can now run the set-up and the instructions move to the Makefile
```
make setup
```

5. It's not clear what I need to do for:
https://github.com/AdaCore/spark2014/blob/33f3c141e821d980d2ed99cbcb2892646e53f266/Makefile#L7
the following seems to sort of work:
```
cd ..
git clone git://gcc.gnu.org/git/gcc.git
cd -
ln --symbolic ../../gcc/gcc/ada gnat2why/gnat_src
```
but I suspect this is the wrong version.  Which repository should I use?  Which commit? It feels like this would be a lot easier if this was a submodule; is there a reason it isn't?

6. It is also not clear what I need to do for:
https://github.com/AdaCore/spark2014/blob/33f3c141e821d980d2ed99cbcb2892646e53f266/Makefile#L8
There is `gnat/install/compiler/include/gnatcoll` which is part of the GNAT install?  Is this sufficient?  Do I need to provide configuration for this?  If so what?

7. Then build and install
```
make
make install-all
```

8. Build the solvers independently using their own build infrastructures.

My apologies if I have missed something obvious.  All input, hints, suggestions and tips very much appreciated.

**Comment by kanigsson** [comment]
> apt-get install ocaml menhir libnum-ocaml-dev libmenhir-ocaml-dev python3-sphinx

There might be more needed, depending on if you want to build alt-ergo. But the easiest is to just try and find out. We use opam internally instead of distribution-provided ocaml install, so that would be another option.

> 2. Install the GNAT 2020 Community edition:

GNAT Community 2021 was released last year: https://www.adacore.com/download

> 3. Clone the repo including submodules:
> ( Is there a more modern version than the GPL-2020 one? Will there be a GPL-2021 or a GPL-2022 version? )

I think we just forgot to create the proper branch. You should be able to use 0cf262a69f333330ded4d99a585cabd4d066fca1 for GNAT Community 2021. As an alternative, you can use the fsf branch with the FSF compiler and sources.

> ```
> cd ..
> git clone git://gcc.gnu.org/git/gcc.git
> cd -
> ln --symbolic ../../gcc/gcc/ada gnat2why/gnat_src
> ```
> but I suspect this is the wrong version. Which repository should I use? Which commit? 

The above is exactly correct if you use the fsf branch + FSF compiler. If you use GNAT Community 2021, you need to use the sources of that. The download link I pointed you to also allows you to download the corresponding sources.

> It feels like this would be a lot easier if this was a submodule; is there a reason it isn't?

Yes, the corresponding git repository isn't public.

>    There is `gnat/install/compiler/include/gnatcoll` which is part of the GNAT install?  Is this sufficient?  Do I need to provide configuration for this?  If so what?

Yes, that should be sufficient.

Please let us know if you run into more issues.
