### ISSUE TITLE
Issues with building the fsf-13 branch of SPARK with gnat-13

### ISSUE THREAD

**Issue by dalybrown** [AdaCore/spark2014#46]
Hello,

I previously was building the `fsf-12` branch of SPARK with `gnat-12` in a Debian docker container run on a Mac M1 and it worked fine. We decided to move to `gnat-13` and update SPARK too. I ran into some new issues while trying to build.

Originally, I used the `make setup`, `make`, and `make install-all` targets for the `fsf-12` branch. This worked fine; although, it wasn't clear to me if I should be building the nightly targets which use the production flags.

When updating to the `fsf-13` branch and the `releases/gcc-13.2.0` tag of the compiler, I can no longer make the default target because of the `-gnatw.a` switch. I get the following errors:

```
280.4 ce_parsing.adb:894:22: warning: in instantiation at line 381 [-gnatw.a]
280.4 ce_parsing.adb:894:22: warning: assertion will fail at run time [-gnatw.a]
287.6 
287.6    compilation of ce_parsing.adb failed
```

To work around this, I can use different targets to build the production version (which presumable use the `-gnatwn` switch):

```
make setup
make gnat2why-nightly
make gnatprove-nightly
make why3
make install-all
```

This seems to get it to build. However, when using `gnatprove` to prove some code, I run into a new issue:

```
Phase 1 of 2: generation of Global contracts ... 
fatal error, run-time library not installed correctly
cannot locate file system.ads
compilation abandoned
gnatprove: error during generation of Global contracts
```

This error did not happen when building the `fsf-12` branch. It seems that it doesn't know where the runtime is. Perhaps this is related to `gnat-13` in debian, or something changed in `gnatprove`. Either way, I can work around this by adding the `-RTS` switch to `gnatprove`: `--RTS=/usr/lib/gcc/aarch64-linux-gnu/13`.

I am wondering if this is a bug in the spark installation code, in `gnat-13`, or in the way I am building it. I think the default make target should probable build regardless. Regarding specifying the `RTS` switch, I couldn't find it in the docs anywhere stating it is mandatory now.

On a related note, which branch of `gcc` does the `fsf` branch of spark follow? I noticed that branch is much more up to date than `fsf-13`; it would be nice to keep my version of gnatprove up to date with the latest changes. (I wasn't able to get the `fsf` branch to build, but I didn't spend much time on it.) Thanks!

**Comment by kanigsson** [comment]
Hi Daly,

I hope I can provide some answers to your questions.
- The `fsf-13` branch is supposed to follow the GCC release branch 13. We haven't tested this recently, so there could be some issues. Also, it's not tested on M1.
- The `fsf` branch is supposed to follow the GCC master branch.
- The `make` default target is intended for developers or a local install from sources. It sets things up so that gnatprove uses the runtime provided by the compiler used for compilation.
- The `*-nightly` build targets are for the production build. They require that a runtime is packaged with SPARK under `libexec/spark`. A simple (but disk-space consuming) option is to place a copy of your `gcc` install there.
- I'm not sure about the extra warning you get during compilation. It could be related to M1 as well. But the code could be wrong regardless, we will look into this.
- This warning probably results in one of the two situations: 1) it breaks gnatprove entirely (it always fails) or 2) you are unlikely to exercise the code and can ignore it. Given that you were able to run gnatprove with `--RTS` switch, it's likely (2) and you can ignore it. To ignore it, you can either use production builds, or use the devel builds and edit the `gnat2why_gnat.gpr` file to add `-gnatwn` to the compilation switches (let us know if you need help with that).

**Comment by dalybrown** [comment]
Thanks. I can just use the production version and use the RTS flag... seems to work. I'm going to try to get the fsf + main branch of gcc to build so I can keep up to date with SPARK updates.

**Comment by dalybrown** [comment]
When I did try to build the `fsf` branch I get the following:

```
89.92 spark_definition.adb:3212:22: error: "Error_Msg_Code" is undefined (more references follow)
89.93 spark_definition.adb:5878:36: error: "Pragma_Exceptional_Cases" is undefined (more references follow)
89.93 spark_definition.adb:5970:36: error: "Pragma_Always_Terminates" is undefined (more references follow)
89.93 spark_definition.adb:6408:47: error: unmatched actual "Skip_Overridden" in call
89.93 spark_definition.adb:6411:49: error: unmatched actual "Skip_Overridden" in call
89.93 spark_definition.adb:9230:15: error: "Pragma_Side_Effects" is undefined
89.93 spark_util.ads:513:27: error: "Is_Function_With_Side_Effects" is undefined (more references follow)
89.93 spark_util-subprograms.ads:690:04: error: no visible subprogram matches the specification for "Inherited_Subprograms"
90.19 spark_util.ads:513:27: error: "Is_Function_With_Side_Effects" is undefined
90.19 spark_util-subprograms.ads:690:04: error: no visible subprogram matches the specification for "Inherited_Subprograms"
96.02 
96.02    compilation of gnat2why-driver.adb failed
96.02    compilation of spark_definition.adb failed
```

Any ideas of what the issue is? Thanks!

**Comment by kanigsson** [comment]
Did you use the `gcc` master branch? If not, that would explain it. Note that in my experiments indeed `fsf` branch doesn't compile with gnat `13.2.x` release due to some other issues. So ideally you would build your own gcc or stick with the `fsf-13` branch.

**Comment by dalybrown** [comment]
Exactly my experience. That's what I will do for now (stick with fsf-13) until fsf-14 is released. Thanks for the tips!
