### ISSUE TITLE
build default target.atp

### ISSUE THREAD

**Issue by anmaped** [AdaCore/spark2014#6]
I'm currently installing spark2014 without building the target.atp.

What is missing here? I'm using the gnat-community-2018-windows.

```
$ make install
mkdir -p /cygdrive/c/spark2014/install/bin /cygdrive/c/spark2014/install/share/spark/config /cygdrive/c/spark2014/install/share/spark/theories \
  /cygdrive/c/spark2014/install/share/spark/runtimes /cygdrive/c/spark2014/install/include/spark /cygdrive/c/spark2014/install/lib/gnat
Generate default target.atp in /cygdrive/c/spark2014/install/bin:
gnatmake -q -c -u -gnats spark2014vsn.ads \
  -gnatet=/cygdrive/c/spark2014/install/bin/target.atp
cannot create file /cygdrive/c/spark2014/install/bin/target.atp
gnatmake: "spark2014vsn.ads" compilation error
make: *** [Makefile:102: install] Error 4
```

**Comment by yannickmoy** [comment]
Note that GNAT Community 2018 comes with SPARK, so you don't need to build/install SPARK from sources. That being said, after you build SPARK from sources, you should use "make install-all" instead of "make install" as indicated in the Makefile (which calls "make install"). Here it seems that you do not have the proper user rights to install in /cygdrive/c/spark2014/install/bin. You should check the rights of this directory.

**Comment by anmaped** [comment]
> 
> 
> Note that GNAT Community 2018 comes with SPARK, so you don't need to build/install SPARK from sources. That being said, after you build SPARK from sources, you should use "make install-all" instead of "make install" as indicated in the Makefile (which calls "make install"). Here it seems that you do not have the proper user rights to install in /cygdrive/c/spark2014/install/bin. You should check the rights of this directory.

Thanks for your support. However, no matter what permissions I have it simply doesn't work inside Cygwin.
I will try to execute the command outside Cygwin since everything else is correctly installed (I mean all the command inside make install-all).

**Comment by yannickmoy** [comment]
can you try running the gnatmake command? does it work?
can you change the switches on the gnatmake command to locate the problem?
thx

**Comment by anmaped** [comment]
It's simply because gnatmake accepts windows paths and not Cygwin paths. My workaround was doing
```
gnatmake -q -c -u -gnats spark2014vsn.ads -gnatet=target.atp
```
and then cp in the makefile.

**Comment by yannickmoy** [comment]
aha! thanks, we'll see how to adapt the scripts for that case.

**Comment by kanigsson** [comment]
The easiest way to avoid such issues is to work in a folder where cygwin path and windows path are the same. You can achieve this by creating a path e.g. C:\spark2014 (you seem to have that already) and mount it in cygwin as /spark2014. For example put this line in your /etc/fstab:

    c:/spark2014 /spark2014 ntfs binary,posix=0,noacl 0 0

In fact instead of doing that for all tools (gnat, spark2014, ...), you could have a workspace in C:\work or something like that.
